version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:                                      # 볼륨설정, 호스트:컨테이너
      - ./db/conf.d:/etc/mysql/conf.d             # MySQL 설정
      - ./db/initdb.d:/docker-entrypoint-initdb.d # 테이블 create, insert

    ports: # 외부로 노출시킬 port 입니다.
      - "3306:3306"
    environment: # 환경 변수
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123 # https://csksoft.tistory.com/69 디비버 연결 시 오류 참조
      - TZ=Asia/Seoul
    command:
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8  
      --collation-server=utf8_general_ci

    
